# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 02:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 2, 36, 41, 794270, tzinfo=utc)),
        ),
    ]
