# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 04:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20171021_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('reg_time', models.DateTimeField(default=datetime.datetime(2017, 10, 22, 4, 45, 16, 376728, tzinfo=utc))),
            ],
            options={
                'ordering': ('-reg_time',),
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 4, 45, 16, 375728, tzinfo=utc)),
        ),
    ]
