# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20171022_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 10, 46, 26, 266611, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 10, 46, 26, 266611, tzinfo=utc)),
        ),
    ]
